slider_plot()


function [] = slider_plot()
S.x = linspace(0, 1, 200);

S.figure = figure('units','normalized',...
              'name','Concat Two Neurons');
          
S.axes = axes('unit','normalized',...
          'position',[0.1 0.45 0.8 0.45]);

S.sigmoid = @(x, W, b) 1./(1+exp(-(W*x+b)));

S.W1 = 1;
S.b1 = 0;
S.W2 = 1;
S.b2 = 0;

S.plot = plot(S.x,S.sigmoid(S.x, S.W1, S.b1) + S.sigmoid(S.x, S.W2, S.b2));

update(S);

S.W1Slider = uicontrol('style','slider',...
               'unit','normalized',...
               'position',[0.1 0.35 0.8 0.01],...
               'min',-30,'max',30,'value', S.W1,...
               'sliderstep',[0.01 0.01],...
               'callback', {@SliderCB, 'W1'}); 
           
txtW1 = uicontrol('Style','text',...
     'unit','normalized',...
               'position',[0.1 0.36 0.8 0.05],...
     'String','W1');
 
S.b1Slider = uicontrol('style','slide',...
               'unit','normalized',...
               'position',[0.1 0.25 0.8 0.01],...
               'min',-30,'max',30,'value', S.b1,...
               'sliderstep',[0.01 0.01],...
               'callback', {@SliderCB, 'b1'});

txtb1 = uicontrol('Style','text',...
     'unit','normalized',...
               'position',[0.1 0.26 0.8 0.05],...
     'String','b1');      
 
S.W2Slider = uicontrol('style','slider',...
               'unit','normalized',...
               'position',[0.1 0.15 0.8 0.01],...
               'min',-30,'max',30,'value', S.W2,...
               'sliderstep',[0.01 0.01],...
               'callback', {@SliderCB, 'W2'}); 
           
txtW2 = uicontrol('Style','text',...
     'unit','normalized',...
               'position',[0.1 0.16 0.8 0.05],...
     'String','W2');
 
S.b2Slider = uicontrol('style','slide',...
               'unit','normalized',...
               'position',[0.1 0.05 0.8 0.01],...
               'min',-30,'max',30,'value', S.b2,...
               'sliderstep',[0.01 0.01],...
               'callback', {@SliderCB, 'b2'});

txtb2 = uicontrol('Style','text',...
     'unit','normalized',...
               'position',[0.1 0.06 0.8 0.05],...
     'String','b2');   
 
guidata(S.figure, S);  % Store S structure in the figure
end

% Callback for all sliders defined above
function SliderCB(aSlider, EventData, Param)
S = guidata(aSlider);  % Get S structure from the figure
S.(Param) = get(aSlider, 'Value');  % Any of the 'a', 'b', etc. defined
update(S);  % Update the plot values
guidata(aSlider, S);  % Store modified S in figure
end

function update(S)
y = S.sigmoid(S.x, S.W1, S.b1) + S.sigmoid(S.x, S.W2, S.b2);
set(S.plot, 'YData', y);  % Replace old plot with new plotting values
axis([0,1,0,2]);
title(['y = \sigma(', num2str(S.W1), 'x +', num2str(S.b1), ') + \sigma(', num2str(S.W2), 'x +', num2str(S.b2), ')'], 'FontSize', 30)
end